default:
  image: forgejo.puffer.fish/matthieu/base-images/fedora-c-build:latest # Public image with debian & required build tools

stages:
  - ci

'Build & Test':
  stage: ci

  parallel:
    matrix:
      - TARGET: [x86_64-redhat-linux-gnu, x86_64-w64-windows-gnu]
        PROFILE: [debug, release]
  
  script:
    - make -s build -j$(nproc) TARGET=$TARGET PROFILE=$PROFILE
    - make -s test TARGET=$TARGET PROFILE=$PROFILE

  artifacts:
    when: always
    paths:
      - ./out/$PROFILE/$TARGET/bin/tests/*.xml
      - ./out/$PROFILE/$TARGET/bin/cli*
      - ./out/$PROFILE/$TARGET/bin/gui*
    reports:
      junit: ./out/$PROFILE/$TARGET/bin/tests/*.xml

