default:
  image: forgejo.puffer.fish/matthieu/base-images/tn-pp2i-ci-image:latest # Public image with debian & required build tools

.targets: &targets
  - x86_64-redhat-linux-gnu
  - x86_64-w64-mingw64
  - x86_64-w64-mingw32

.profiles: &profiles 
  - debug
  - release

stages:
  - build
  - test
  - docs

'Build':
  stage: build

  parallel:
    matrix:
      - TARGET: *targets
        PROFILE: *profiles
  
  script:
    - make -s clean TARGET=$TARGET PROFILE=$PROFILE
    - bear --output ./out/$PROFILE/$TARGET/compile_commands.json -- make -s clean build -j$(nproc) TARGET=$TARGET PROFILE=$PROFILE

  artifacts:
    when: always
    paths:
      - ./out/$PROFILE/$TARGET

'Tidy':
  stage: test
  parallel:
    matrix:
      - TARGET: *targets
        PROFILE: *profiles

  needs:
    - job: 'Build'
      parallel:
        matrix:
          - TARGET: ['$[[ matrix.TARGET ]]']
            PROFILE: ['$[[ matrix.PROFILE ]]']

  script:
    - run-clang-tidy -p out/$PROFILE/$TARGET/

'Test':
  stage: test

  needs:
    - job: 'Build'
      parallel:
        matrix:
          - TARGET: ['$[[ matrix.TARGET ]]']
            PROFILE: ['$[[ matrix.PROFILE ]]']

  parallel:
    matrix:
      - TARGET: *targets
        PROFILE: *profiles
  
  script:
    - make -s test TARGET=$TARGET PROFILE=$PROFILE

  artifacts:
    when: always
    paths:
      - ./out/$PROFILE/$TARGET/bin/tests/*.xml
    reports:
      junit: ./out/$PROFILE/$TARGET/bin/tests/*.xml

'Lint':
  stage: test
  needs: []
  script:
    - make -s check

'Docs':
  stage: docs
  script:
    - make docs
  artifacts:
    when: always
    paths:
      - ./public
