default:
  image: forgejo.puffer.fish/matthieu/base-images/fedora-c-build:latest # Public image with debian & required build tools

stages:
  - build
  - test
  - docs

'Build':
  stage: build

  parallel:
    matrix:
      - TARGET: [x86_64-redhat-linux-gnu, x86_64-w64-windows-gnu]
        PROFILE: [debug, release]
  
  script:
    - make -s build -j$(nproc) TARGET=$TARGET PROFILE=$PROFILE

  artifacts:
    when: always
    paths:
      - ./out/$PROFILE/$TARGET/bin/cli*
      - ./out/$PROFILE/$TARGET/bin/sdl*

'Test':
  stage: test

  parallel:
    matrix:
      - TARGET: [x86_64-redhat-linux-gnu, x86_64-w64-windows-gnu]
        PROFILE: [debug, release]
  
  script:
    - make -s test -j$(nproc) TARGET=$TARGET PROFILE=$PROFILE

  artifacts:
    when: always
    paths:
      - ./out/$PROFILE/$TARGET/bin/tests/*.xml
    reports:
      junit: ./out/$PROFILE/$TARGET/bin/tests/*.xml

'Docs':
  stage: docs
  script:
    - make docs
  artifacts:
    when: always
    paths:
      - ./public
