@startuml carcassonne

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

class model.Position {
    - x : Integer
    - y : Integer
}

class model.Tile {
    
}

class model.Face {
    
}

class model.Meeple {

}

class model.Player {
    - id : Integer
    - name : String
    - score : Integer
}

enum model.Type <<enum>>{
    VILLAGE
    TOWN
    TOWNWITHSHIELD
    ABBEY
    ROAD
}

enum model.Orientation <<enum>>{
    NORTH
    SOUTH
    WEST
    EAST
    CENTER
}

enum model.PlayerType <<enum>>{
    IA
    HUMAN
}

class Game {
    - current_player_id : Integer
}

model.Tile o-r-> "1 \n -position" model.Position : Se trouve à >
model.Tile o--> "5 \n -faces[]" model.Face : Possède >
model.Tile o--> "0..n \n -meeples[]" model.Meeple : Contient >

model.Face o-r-> "1 \n -orientation" model.Orientation : Possède >
model.Face o-d-> "1 \n -type" model.Type : Est un >

model.Meeple o-u-> "0..1 \n -position" model.Position : Se trouve à >
model.Meeple o--> "0..1 \n -face" model.Face : Se trouve sur >

model.Player "1 \n -player" o-d-> "8 \n -meeples" model.Meeple : Possède >
model.Player  o-r-> "1 \n -type" model.PlayerType : Est un >

Game *--> "2..5 \n -players" Player : Contient >
Game *--> "n \n -players" Tile : Contient >

@enduml