@startuml carcassonne

skinparam style strictuml
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
hide empty members

class carcassonne.Position {
    - x : int
    - y : int
}

class carcassonne.Tile {
    
}

class carcassonne.Face {
    
}

class carcassonne.Meeple {

}

class carcassonne.Player {
    - id : int
    - name : char*
    - score : int
}

enum carcassonne.Type <<enum>>{
    VILLAGE
    TOWN
    TOWNWITHSHIELD
    ABBEY
    ROAD
}

enum carcassonne.Orientation <<enum>>{
    NORTH
    SOUTH
    WEST
    EAST
    CENTER
}

enum carcassonne.PlayerType <<enum>>{
    IA
    HUMAN
}

class carcassonne.Game {
    - current_player_id : int
    - max_turns : int
    - turns_count : int
    - seed : int
    - human_player_count : int
    - total_player_count : int
    + make_turn()
    + ask_player_action()
    + place_tile()
    + place_meeple()
    + get_current_player() : Player*
}

class EngineSDL {
    create_game(max_turns : int, turns_count : int, seed : int, human_player_count : int, total_player_count : int) : Game*
    start_game(game : Game*) : void
    destroy_game(game : Game*) : void
}

class EngineCLI {
    create_game(max_turns : int, turns_count : int, seed : int, human_player_count : int, total_player_count : int) : Game*
    start_game(game : Game*) : void
    destroy_game(game : Game*) : void
}

class ai.AIEngine {
    + makeDecision(game : Game*)
}

class AIState {}

class MainCLI {}
class MainSDL {}

Tile o-r-> "1 \n -position" Position : Se trouve à >
Tile o--> "5 \n -faces**" Face : Possède >
Tile o--> "0..n \n -meeples**" Meeple : Contient >

Face o-r-> "1 \n -orientation" Orientation : Possède >
Face o-d-> "1 \n -type" Type : Est un >

Meeple o-u--> "0..1 \n -position" Position : Se trouve à >
Meeple o--> "0..1 \n -face" Face : Se trouve sur >

Player "1 \n -player" o-d-> "8 \n -meeples**" Meeple : Possède >
Player  o-d-> "1 \n -type" PlayerType : Est un >

Game *--> "2..5 \n -players**" Player : Contient >
Game *--> "n \n -tiles***" Tile : Contient >

EngineSDL *--> "1 \n -game*" Game : Joue >

EngineCLI *--> AIEngine : "Fait jouer" >
EngineSDL *--> AIEngine : "Fait jouer" >

MainSDL ..> EngineSDL  : "<<uses>>"

EngineCLI *--> "1 \n -game*" Game : Joue >
MainCLI ..> EngineCLI  : "<<uses>>

Player *--> AIState : Utilise >
AIEngine o--> AIState : Utilise >

@enduml